# Generated by Django 5.1.3 on 2024-12-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0005_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='review_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='rating',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
