# Generated by Django 5.1.3 on 2024-12-23 18:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0007_alter_rating_rating_alter_rating_review_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='woofspotevent',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
