# Generated by Django 5.1.3 on 2024-12-27 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0008_woofspotevent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_ratings', to='event_app.woofspotevent'),
        ),
    ]
