# Generated by Django 5.1.3 on 2025-01-14 17:29

import event_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0010_alter_woofspotevent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woofspotevent',
            name='event_date',
            field=models.DateField(validators=[event_app.models.date_validation]),
        ),
        migrations.AlterField(
            model_name='woofspotevent',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='woofspotevent',
            name='title',
            field=models.CharField(max_length=55, unique=True),
        ),
    ]
